In [7]:
import numpy as np
import pandas as pd

In [10]:
from google.colab import files
upload = files.upload()

Saving data.csv to data.csv


In [11]:
data = pd.read_csv('data.csv')
data.head()

Aplicant  GPA  Psychology  Interview  Result
0         1    3           2          1       1
1         2    3           1          1       1
2         3    3           1          0       1
3         4    3           2          0       0
4         5    2           3          1       1

In [12]:
# menampilkan informasi data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Aplicant    11 non-null     int64
 1   GPA         11 non-null     int64
 2   Psychology  11 non-null     int64
 3   Interview   11 non-null     int64
 4   Result      11 non-null     int64
dtypes: int64(5)
memory usage: 568.0 bytes


In [13]:
# Mengecek apakah ada deret yang kosong
data.empty

False

In [14]:
# Melihat ukuran dari data
data.size

55

In [16]:
# Variabel independen
x = data.drop(['Result'], axis = 1)
x.head()

Aplicant  GPA  Psychology  Interview
0         1    3           2          1
1         2    3           1          1
2         3    3           1          0
3         4    3           2          0
4         5    2           3          1

In [17]:
# Variabel dependen
y = data['Result']
y.head()

0    1
1    1
2    1
3    0
4    1
Name: Result, dtype: int64

In [18]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [19]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([3., 5.])

In [20]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1])

In [21]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[0., 1.],
       [0., 1.],
       [0., 1.]])

In [22]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3]])

In [23]:
# Merapikan hasil confusion matrix
y_actual1 = pd.Series([1, 0,1,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0], name = 'actual')
y_pred1 = pd.Series([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1], name = 'prediction')
df_confusion = pd.crosstab(y_actual1, y_pred1)
df_confusion

prediction  0  1
actual          
0           7  2
1           1  8

In [24]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         3

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

